# Generated by Django 4.1.5 on 2023-01-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_movie_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.FloatField(default=0.0),
        ),
    ]
